In [18]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [19]:
import pandas as pd
import numpy as np

In [21]:
a = np.arange(15).reshape(3, 5)
a.size
a.shape
a.dtype
a.itemsize
a.data

15

(3, 5)

dtype('int32')

4

In [35]:
b = np.array([[1, 0.2],[2, 0]], dtype=complex)
b

array([[1. +0.j, 0.2+0.j],
       [2. +0.j, 0. +0.j]])

In [45]:
a = np.linspace(0, 2*np.pi, 4)
x = np.sin(a)
a
x
np.sin(np.pi)

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

1.2246467991473532e-16

In [51]:
c = np.random.rand(3,2)
c

array([[0.33177685, 0.73900453],
       [0.4893199 , 0.71588012],
       [0.59609576, 0.30941781]])

In [64]:
a = np.array([10,20,30,40])
b = np.arange(4)
c = b + a
c < 35

array([ True,  True,  True, False])

In [69]:
a = np.random.randn(2,2)
b = np.random.randn(2,2)
a * b
a @ b
a.dot(b)
b.dot(a)

array([[-0.94695464, -0.07011787],
       [-2.55940704,  2.20027672]])

array([[-1.24473975, -0.08054945],
       [ 3.3885147 ,  1.59762678]])

array([[-1.24473975, -0.08054945],
       [ 3.3885147 ,  1.59762678]])

array([[-1.54960457,  0.58755202],
       [-2.09755574,  1.90249161]])

In [82]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
b += a
b
b.cumsum(axis=1)

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

array([[ 3.51182162,  7.46228532, 10.60644493],
       [ 3.94864945,  7.2604809 , 10.68380735]])

In [89]:
x = np.array([1, 2, 4, 7, 0])
a = np.diff(x)
np.diff(a)

array([  1,   1, -10])

In [93]:
def f(x, y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int)
b
b[1:3, :]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [101]:
c = np.random.rand(2,2,3)*10
c.shape
c[1,...]
c[...,2]

(2, 2, 3)

array([[4.15339009, 4.05657883, 3.49001618],
       [1.91650665, 9.00963456, 2.71466651]])

array([[5.69962377, 1.0194961 ],
       [3.49001618, 2.71466651]])

In [105]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
b.flat

In [106]:
a = np.arange(35).reshape(5,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [112]:
a[np.array([0,2,4]), np.array([0,1,2])]

array([ 0, 15, 30])

In [115]:
a.T

array([[ 0,  7, 14, 21, 28],
       [ 1,  8, 15, 22, 29],
       [ 2,  9, 16, 23, 30],
       [ 3, 10, 17, 24, 31],
       [ 4, 11, 18, 25, 32],
       [ 5, 12, 19, 26, 33],
       [ 6, 13, 20, 27, 34]])

In [119]:
a = np.floor(np.random.rand(2,2)*10)
b = np.floor(np.random.rand(2,2)*10)
a
b

array([[9., 8.],
       [1., 1.]])

array([[7., 1.],
       [6., 6.]])

In [123]:
np.hstack((a,b))
np.column_stack((a,b))

array([[9., 8., 7., 1.],
       [1., 1., 6., 6.]])

array([[9., 8., 7., 1.],
       [1., 1., 6., 6.]])

In [125]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.vstack((a,b))
np.hstack((a,b))

array([[4., 2.],
       [3., 8.]])

array([4., 2., 3., 8.])

In [130]:
a = np.arange(12)**2
j = np.array([[3, 4], [9, 7]])
a
a[j]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [131]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])